---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: labspect
  namespace: flux-system
spec:
  image: ghcr.io/mcpavao/labspect
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: labspect
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: labspect
  filterTags:
    pattern: '^sha-(?P<sha>[a-f0-9]+)$'
    extract: '$sha'
  policy:
    alphabetical:
      order: asc
